---
version: 1
database:
  production: pomodori_production.sqlite3
  test: pomodori_test.sqlite3
  development: pomodori_development.sqlite3
pomodoro:
  summary: Working on something awesome
  duration: 25
  count_to_long_break: 4
pausa:
  summary: Taking a short break
  duration: 5
long_break:
  summary: Taking a long break
  duration: 15
