---
version: 1
database:
  production: pomodori_production.sqlite3
  test: pomodori_test.sqlite3
  development: pomodori_development.sqlite3
pomodoro:
  summary: Working on something awesome
  duration: 25
  count_to_lunga_pausa: 4
pausa:
  summary: Taking a short break
  duration: 5
lunga_pausa:
  summary: Taking a long break
  duration: 15
